# Generated by Django 5.2.1 on 2025-06-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0010_alter_driver_team_alter_race_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='driver',
            new_name='drivers',
        ),
    ]
